
spring:
  main:
    banner-mode: "off"
    web-environment: false
---
spring:
  profiles: default
pampas:
  db:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pampas?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 123456
  group: pampas_prod
  port: 9002
  id: my_host_${pampas.group}-${pampas.port}
  worker: 2
